using GTANetworkAPI;
using System.Collections.Generic;

namespace PlayerDeath
{
    public static class DeathDicts
    {
        public static readonly Dictionary<uint, string> DeathReasons = new Dictionary<uint, string>
        {
            {(uint)DeathReason.AirstrikeRocket, "air struck rocket" },
            {(uint)DeathReason.Animal, "beasted"},
            {(uint)DeathReason.BarbedWire, "barbed wire"},
            {(uint)DeathReason.Bleeding, "bleeded out"},
            {(uint)DeathReason.Briefcase, "briefcase"},
            {(uint)DeathReason.Briefcase02, "briefcase"},
            {(uint)DeathReason.Cougar, "a beasted Cougar"},
            {(uint)DeathReason.Drowning, "drowned"},
            {(uint)DeathReason.DrowningInVehicle, "drowned"},
            {(uint)DeathReason.ElectricFence, "leccy fence"},
            {(uint)DeathReason.Exhaustion, "from exhaustion"},
            {(uint)DeathReason.Explosion, "blew up"},
            {(uint)DeathReason.Fall, "fell"},
            {(uint)DeathReason.Fire, "burned"},
            {(uint)DeathReason.HeliCrash, "helicopter crash"},
            {(uint)DeathReason.HitByWaterCannon, "water cannon"},
            {(uint)DeathReason.RammedByCar, "rammed by car"},
            {(uint)DeathReason.RunOverByCar, "run over by car"},
            {(uint)DeathReason.VehicleRocket, "vehicle rocket"},
            {(uint)WeaponHash.AssaultRifle,"assault rifle"},
            {(uint)WeaponHash.AssaultSMG,"assault smg"},
            {(uint)WeaponHash.AssaultShotgun ,"assault shotgunned"},
            {(uint)WeaponHash.SniperRifle           ,"sniped"},
            {(uint)WeaponHash.FireExtinguisher      ,"extinguished"},
            {(uint)WeaponHash.CompactGrenadeLauncher,"compact grenade"},
            {(uint)WeaponHash.Snowball      ,"snowballed"},
            {(uint)WeaponHash.VintagePistol ,"vintage pistol"},
            {(uint)WeaponHash.CombatPDW     ,"combat pdw"},
            {(uint)WeaponHash.HeavySniper   ,"heavy sniped"},
            {(uint)WeaponHash.SweeperShotgun,"sweeper shotgunned"},
            {(uint)WeaponHash.MicroSMG      ,"smg"},
            {(uint)WeaponHash.Wrench        ,"hit by wrench"},
            {(uint)WeaponHash.Pistol        ,"pistol"},
            {(uint)WeaponHash.PumpShotgun   ,"pump action shotgunned"},
            {(uint)WeaponHash.APPistol      ,"AP Pistol"},
            {(uint)WeaponHash.Ball          ,"hit by ball"},
            {(uint)WeaponHash.Molotov       ,"burnt by Molotov"},
            {(uint)WeaponHash.SMG           ,"smg"},
            {(uint)WeaponHash.StickyBomb    ,""},
            {(uint)WeaponHash.PetrolCan     ,""},
            {(uint)WeaponHash.StunGun       ,""},
            {(uint)WeaponHash.HeavyShotgun  ,""},
            {(uint)WeaponHash.Minigun       ,""},
            {(uint)WeaponHash.GolfClub      ,""},
            {(uint)WeaponHash.FlareGun      ,""},
            {(uint)WeaponHash.Flare         ,""},
            {(uint)WeaponHash.GrenadeLauncherSmoke  ,""},
            {(uint)WeaponHash.Hammer         ,""},
            {(uint)WeaponHash.CombatPistol   ,""},
            {(uint)WeaponHash.Gusenberg      ,""},
            {(uint)WeaponHash.CompactRifle   ,""},
            {(uint)WeaponHash.HomingLauncher ,""},
            {(uint)WeaponHash.Nightstick     ,""},
            {(uint)WeaponHash.Railgun        ,""},
            {(uint)WeaponHash.SawnOffShotgun ,""},
            {(uint)WeaponHash.BullpupRifle   ,""},
            {(uint)WeaponHash.Firework       ,""},
            {(uint)WeaponHash.CombatMG       ,""},
            {(uint)WeaponHash.CarbineRifle   ,""},
            {(uint)WeaponHash.Crowbar        ,""},
            {(uint)WeaponHash.Flashlight     ,""},
            {(uint)WeaponHash.Dagger         ,""},
            {(uint)WeaponHash.Grenade        ,""},
            {(uint)WeaponHash.PoolCue        ,""},
            {(uint)WeaponHash.Bat            ,""},
            {(uint)WeaponHash.Pistol50       ,""},
            {(uint)WeaponHash.Knife          ,""},
            {(uint)WeaponHash.MG             ,""},
            {(uint)WeaponHash.BullpupShotgun ,""},
            {(uint)WeaponHash.BZGas          ,""},
            {(uint)WeaponHash.Unarmed        ,""},
            {(uint)WeaponHash.GrenadeLauncher,""},
            {(uint)WeaponHash.NightVision    ,""},
            {(uint)WeaponHash.Musket         ,""},
            {(uint)WeaponHash.ProximityMine  ,""},
            {(uint)WeaponHash.AdvancedRifle  ,""},
            {(uint)WeaponHash.RPG            ,""},
            {(uint)WeaponHash.PipeBomb       ,""},
            {(uint)WeaponHash.MiniSMG        ,""},
            {(uint)WeaponHash.SNSPistol      ,""},            
            {(uint)WeaponHash.SpecialCarbine ,"carbined"},
            {(uint)WeaponHash.Revolver       ,"revolvered"},
            {(uint)WeaponHash.MarksmanRifle  ,"marksman rifled"},
            {(uint)WeaponHash.BattleAxe      ,"battle axed"},
            {(uint)WeaponHash.HeavyPistol    ,"heavey pistol"},
            {(uint)WeaponHash.KnuckleDuster  ,"knuckle dustered"},
            {(uint)WeaponHash.MachinePistol  ,"machine pistol"},
            {(uint)WeaponHash.MarksmanPistol ,"marksman pistol"},
            {(uint)WeaponHash.Machete        ,"chopped by machete"},
            {(uint)WeaponHash.SwitchBlade    ,"sliced with switchblade"},
            {(uint)WeaponHash.DoubleBarrelShotgun,"double barreled"},
            {(uint)WeaponHash.Hatchet,"hatchet"},
            {(uint)WeaponHash.Bottle,"bottled"},
            {(uint)WeaponHash.Parachute,"by parachute"},
            {(uint)WeaponHash.SmokeGrenade,"smoke grenaded"},
        };
    }
}
