using GTANetworkAPI;
using System.Collections.Generic;
using System.Resources;

namespace PlayerDeath
{
    public static class DeathDicts
    {
        private static ResourceManager _dStrings;

        public static readonly Dictionary<uint, string> DeathReasons = null;

        static DeathDicts()
        {
            _dStrings = deathstrings.ResourceManager;

            DeathReasons = new Dictionary<uint, string>
            {
                            {(uint)DeathReason.AirstrikeRocket,     _dStrings.GetString(DeathReason.AirstrikeRocket.ToString()) },
            {(uint)DeathReason.Animal,              _dStrings.GetString(DeathReason.Animal.ToString()) },
            {(uint)DeathReason.BarbedWire,          _dStrings.GetString(DeathReason.BarbedWire.ToString()) },
            {(uint)DeathReason.Bleeding,            _dStrings.GetString(DeathReason.Bleeding.ToString()) },
            {(uint)DeathReason.Briefcase,           _dStrings.GetString(DeathReason.Briefcase.ToString()) },
            {(uint)DeathReason.Briefcase02,         _dStrings.GetString(DeathReason.Briefcase02.ToString()) },
            {(uint)DeathReason.Cougar,              _dStrings.GetString(DeathReason.Cougar.ToString()) },
            {(uint)DeathReason.Drowning,            _dStrings.GetString(DeathReason.Drowning.ToString()) },
            {(uint)DeathReason.DrowningInVehicle,   _dStrings.GetString(DeathReason.DrowningInVehicle.ToString()) },
            {(uint)DeathReason.ElectricFence,       _dStrings.GetString(DeathReason.ElectricFence.ToString()) },
            {(uint)DeathReason.Exhaustion           ,_dStrings.GetString(DeathReason.Exhaustion              .ToString())},
            {(uint)DeathReason.Explosion            ,_dStrings.GetString(DeathReason.Explosion               .ToString())},
            {(uint)DeathReason.Fall                 ,_dStrings.GetString(DeathReason.Fall                    .ToString())},
            {(uint)DeathReason.Fire                 ,_dStrings.GetString(DeathReason.Fire                    .ToString())},
            {(uint)DeathReason.HeliCrash           ,_dStrings.GetString(DeathReason.HeliCrash              .ToString())},
            {(uint)DeathReason.HitByWaterCannon     ,_dStrings.GetString(DeathReason.HitByWaterCannon        .ToString())},
            {(uint)DeathReason.RammedByCar          ,_dStrings.GetString(DeathReason.RammedByCar             .ToString())},
            {(uint)DeathReason.RunOverByCar         ,_dStrings.GetString(DeathReason.RunOverByCar            .ToString())},
            {(uint)DeathReason.VehicleRocket        ,_dStrings.GetString(DeathReason.VehicleRocket           .ToString())},
            {(uint)WeaponHash.AssaultRifle          ,_dStrings.GetString(WeaponHash.AssaultRifle             .ToString())},
            {(uint)WeaponHash.AssaultSMG           ,_dStrings.GetString(WeaponHash.AssaultSMG              .ToString())},
            {(uint)WeaponHash.AssaultShotgun        ,_dStrings.GetString(WeaponHash.AssaultShotgun           .ToString())},
            {(uint)WeaponHash.SniperRifle           ,_dStrings.GetString(WeaponHash.SniperRifle              .ToString())},
            {(uint)WeaponHash.FireExtinguisher      ,_dStrings.GetString(WeaponHash.FireExtinguisher         .ToString())},
            {(uint)WeaponHash.CompactGrenadeLauncher,_dStrings.GetString(WeaponHash.CompactGrenadeLauncher   .ToString())},
            {(uint)WeaponHash.Snowball       , _dStrings.GetString(WeaponHash.Snowball           .ToString())},
            {(uint)WeaponHash.VintagePistol  , _dStrings.GetString(WeaponHash.VintagePistol      .ToString())},
            {(uint)WeaponHash.CombatPDW      , _dStrings.GetString(WeaponHash.CombatPDW          .ToString())},
            {(uint)WeaponHash.HeavySniper    , _dStrings.GetString(WeaponHash.HeavySniper        .ToString())},
            {(uint)WeaponHash.SweeperShotgun , _dStrings.GetString(WeaponHash.SweeperShotgun     .ToString())},
            {(uint)WeaponHash.MicroSMG       , _dStrings.GetString(WeaponHash.MicroSMG           .ToString())},
            {(uint)WeaponHash.Wrench         , _dStrings.GetString(WeaponHash.Wrench             .ToString())},
            {(uint)WeaponHash.Pistol         , _dStrings.GetString(WeaponHash.Pistol             .ToString())},
            {(uint)WeaponHash.PumpShotgun    , _dStrings.GetString(WeaponHash.PumpShotgun        .ToString())},
            {(uint)WeaponHash.APPistol       , _dStrings.GetString(WeaponHash.APPistol           .ToString())},
            {(uint)WeaponHash.Ball           , _dStrings.GetString(WeaponHash.Ball               .ToString())},
            {(uint)WeaponHash.Molotov        , _dStrings.GetString(WeaponHash.Molotov            .ToString())},
            {(uint)WeaponHash.SMG            , _dStrings.GetString(WeaponHash.SMG                .ToString())},
            {(uint)WeaponHash.StickyBomb     , _dStrings.GetString(WeaponHash.StickyBomb         .ToString())},
            {(uint)WeaponHash.PetrolCan      , _dStrings.GetString(WeaponHash.PetrolCan          .ToString())},
            {(uint)WeaponHash.StunGun        , _dStrings.GetString(WeaponHash.StunGun            .ToString())},
            {(uint)WeaponHash.HeavyShotgun   , _dStrings.GetString(WeaponHash.HeavyShotgun       .ToString())},
            {(uint)WeaponHash.Minigun        , _dStrings.GetString(WeaponHash.Minigun            .ToString())},
            {(uint)WeaponHash.GolfClub       , _dStrings.GetString(WeaponHash.GolfClub           .ToString())},
            {(uint)WeaponHash.FlareGun       , _dStrings.GetString(WeaponHash.FlareGun           .ToString())},
            {(uint)WeaponHash.Flare          , _dStrings.GetString(WeaponHash.Flare              .ToString())},
            {(uint)WeaponHash.GrenadeLauncherSmoke,_dStrings.GetString(WeaponHash.GrenadeLauncherSmoke  .ToString())},
            {(uint)WeaponHash.Hammer              ,_dStrings.GetString(WeaponHash.Hammer                .ToString())},
            {(uint)WeaponHash.CombatPistol        ,_dStrings.GetString(WeaponHash.CombatPistol          .ToString())},
            {(uint)WeaponHash.Gusenberg           ,_dStrings.GetString(WeaponHash.Gusenberg             .ToString())},
            {(uint)WeaponHash.CompactRifle        ,_dStrings.GetString(WeaponHash.CompactRifle          .ToString())},
            {(uint)WeaponHash.HomingLauncher      ,_dStrings.GetString(WeaponHash.HomingLauncher        .ToString())},
            {(uint)WeaponHash.Nightstick          ,_dStrings.GetString(WeaponHash.Nightstick            .ToString())},
            {(uint)WeaponHash.Railgun             ,_dStrings.GetString(WeaponHash.Railgun               .ToString())},
            {(uint)WeaponHash.SawnOffShotgun      ,_dStrings.GetString(WeaponHash.SawnOffShotgun        .ToString())},
            {(uint)WeaponHash.BullpupRifle        ,_dStrings.GetString(WeaponHash.BullpupRifle          .ToString())},
            {(uint)WeaponHash.Firework            ,_dStrings.GetString(WeaponHash.Firework              .ToString())},
            {(uint)WeaponHash.CombatMG            ,_dStrings.GetString(WeaponHash.CombatMG              .ToString())},
            {(uint)WeaponHash.CarbineRifle        ,_dStrings.GetString(WeaponHash.CarbineRifle          .ToString())},
            {(uint)WeaponHash.Crowbar             ,_dStrings.GetString(WeaponHash.Crowbar               .ToString())},
            {(uint)WeaponHash.Flashlight          ,_dStrings.GetString(WeaponHash.Flashlight            .ToString())},
            {(uint)WeaponHash.Dagger              ,_dStrings.GetString(WeaponHash.Dagger                .ToString())},
            {(uint)WeaponHash.Grenade             ,_dStrings.GetString(WeaponHash.Grenade               .ToString())},
            {(uint)WeaponHash.PoolCue             ,_dStrings.GetString(WeaponHash.PoolCue               .ToString())},
            {(uint)WeaponHash.Bat                 ,_dStrings.GetString(WeaponHash.Bat                   .ToString())},
            {(uint)WeaponHash.Pistol50            ,_dStrings.GetString(WeaponHash.Pistol50              .ToString())},
            {(uint)WeaponHash.Knife               ,_dStrings.GetString(WeaponHash.Knife                 .ToString())},
            {(uint)WeaponHash.MG                  ,_dStrings.GetString(WeaponHash.MG                    .ToString())},
            {(uint)WeaponHash.BullpupShotgun      ,_dStrings.GetString(WeaponHash.BullpupShotgun        .ToString())},
            {(uint)WeaponHash.BZGas               ,_dStrings.GetString(WeaponHash.BZGas                 .ToString())},
            {(uint)WeaponHash.Unarmed             ,_dStrings.GetString(WeaponHash.Unarmed               .ToString())},
            {(uint)WeaponHash.GrenadeLauncher     ,_dStrings.GetString(WeaponHash.GrenadeLauncher       .ToString())},
            {(uint)WeaponHash.NightVision         ,_dStrings.GetString(WeaponHash.NightVision           .ToString())},
            {(uint)WeaponHash.Musket              ,_dStrings.GetString(WeaponHash.Musket                .ToString())},
            {(uint)WeaponHash.ProximityMine       ,_dStrings.GetString(WeaponHash.ProximityMine         .ToString())},
            {(uint)WeaponHash.AdvancedRifle       ,_dStrings.GetString(WeaponHash.AdvancedRifle         .ToString())},
            {(uint)WeaponHash.RPG                 ,_dStrings.GetString(WeaponHash.RPG                   .ToString())},
            {(uint)WeaponHash.PipeBomb            ,_dStrings.GetString(WeaponHash.PipeBomb              .ToString())},
            {(uint)WeaponHash.MiniSMG             ,_dStrings.GetString(WeaponHash.MiniSMG               .ToString())},
            {(uint)WeaponHash.SNSPistol           ,_dStrings.GetString(WeaponHash.SNSPistol             .ToString())},
            {(uint)WeaponHash.SpecialCarbine      ,_dStrings.GetString(WeaponHash.SpecialCarbine        .ToString())},
            {(uint)WeaponHash.Revolver            ,_dStrings.GetString(WeaponHash.Revolver              .ToString())},
            {(uint)WeaponHash.MarksmanRifle       ,_dStrings.GetString(WeaponHash.MarksmanRifle         .ToString())},
            {(uint)WeaponHash.BattleAxe           ,_dStrings.GetString(WeaponHash.BattleAxe             .ToString())},
            {(uint)WeaponHash.HeavyPistol         ,_dStrings.GetString(WeaponHash.HeavyPistol           .ToString())},
            {(uint)WeaponHash.KnuckleDuster       ,_dStrings.GetString(WeaponHash.KnuckleDuster         .ToString())},
            {(uint)WeaponHash.MachinePistol       ,_dStrings.GetString(WeaponHash.MachinePistol         .ToString())},
            {(uint)WeaponHash.MarksmanPistol      ,_dStrings.GetString(WeaponHash.MarksmanPistol        .ToString())},
            {(uint)WeaponHash.Machete             ,_dStrings.GetString(WeaponHash.Machete               .ToString())},
            {(uint)WeaponHash.SwitchBlade         ,_dStrings.GetString(WeaponHash.SwitchBlade           .ToString())},
            {(uint)WeaponHash.DoubleBarrelShotgun ,_dStrings.GetString(WeaponHash.DoubleBarrelShotgun   .ToString())},
            {(uint)WeaponHash.Hatchet             ,_dStrings.GetString(WeaponHash.Hatchet               .ToString())},
            {(uint)WeaponHash.Bottle              ,_dStrings.GetString(WeaponHash.Bottle                .ToString())},
            {(uint)WeaponHash.Parachute           ,_dStrings.GetString(WeaponHash.Parachute             .ToString())},
            {(uint)WeaponHash.SmokeGrenade        ,_dStrings.GetString(WeaponHash.SmokeGrenade          .ToString())},
            };
        }        
    }
}
