//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerDeath {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class deathstrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal deathstrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayerDeath.deathstrings", typeof(deathstrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvancedRifle.
        /// </summary>
        internal static string AdvancedRifle {
            get {
                return ResourceManager.GetString("AdvancedRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struck by Airstrike.
        /// </summary>
        internal static string AirstrikeRocket {
            get {
                return ResourceManager.GetString("AirstrikeRocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beasted.
        /// </summary>
        internal static string Animal {
            get {
                return ResourceManager.GetString("Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPistol.
        /// </summary>
        internal static string APPistol {
            get {
                return ResourceManager.GetString("APPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssaultRifle.
        /// </summary>
        internal static string AssaultRifle {
            get {
                return ResourceManager.GetString("AssaultRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssaultShotgun.
        /// </summary>
        internal static string AssaultShotgun {
            get {
                return ResourceManager.GetString("AssaultShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssaultSMG.
        /// </summary>
        internal static string AssaultSMG {
            get {
                return ResourceManager.GetString("AssaultSMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ball.
        /// </summary>
        internal static string Ball {
            get {
                return ResourceManager.GetString("Ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barbed wire.
        /// </summary>
        internal static string BarbedWire {
            get {
                return ResourceManager.GetString("BarbedWire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat.
        /// </summary>
        internal static string Bat {
            get {
                return ResourceManager.GetString("Bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BattleAxe.
        /// </summary>
        internal static string BattleAxe {
            get {
                return ResourceManager.GetString("BattleAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleeding.
        /// </summary>
        internal static string Bleeding {
            get {
                return ResourceManager.GetString("Bleeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle.
        /// </summary>
        internal static string Bottle {
            get {
                return ResourceManager.GetString("Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefcase.
        /// </summary>
        internal static string Briefcase {
            get {
                return ResourceManager.GetString("Briefcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefcase02.
        /// </summary>
        internal static string Briefcase02 {
            get {
                return ResourceManager.GetString("Briefcase02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BullpupRifle.
        /// </summary>
        internal static string BullpupRifle {
            get {
                return ResourceManager.GetString("BullpupRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BullpupShotgun.
        /// </summary>
        internal static string BullpupShotgun {
            get {
                return ResourceManager.GetString("BullpupShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BZGas.
        /// </summary>
        internal static string BZGas {
            get {
                return ResourceManager.GetString("BZGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarbineRifle.
        /// </summary>
        internal static string CarbineRifle {
            get {
                return ResourceManager.GetString("CarbineRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CombatMG.
        /// </summary>
        internal static string CombatMG {
            get {
                return ResourceManager.GetString("CombatMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CombatPDW.
        /// </summary>
        internal static string CombatPDW {
            get {
                return ResourceManager.GetString("CombatPDW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CombatPistol.
        /// </summary>
        internal static string CombatPistol {
            get {
                return ResourceManager.GetString("CombatPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompactGrenadeLauncher.
        /// </summary>
        internal static string CompactGrenadeLauncher {
            get {
                return ResourceManager.GetString("CompactGrenadeLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompactRifle.
        /// </summary>
        internal static string CompactRifle {
            get {
                return ResourceManager.GetString("CompactRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cougar.
        /// </summary>
        internal static string Cougar {
            get {
                return ResourceManager.GetString("Cougar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowbar.
        /// </summary>
        internal static string Crowbar {
            get {
                return ResourceManager.GetString("Crowbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabbed.
        /// </summary>
        internal static string Dagger {
            get {
                return ResourceManager.GetString("Dagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleBarrelShotgun.
        /// </summary>
        internal static string DoubleBarrelShotgun {
            get {
                return ResourceManager.GetString("DoubleBarrelShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drowning.
        /// </summary>
        internal static string Drowning {
            get {
                return ResourceManager.GetString("Drowning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrowningInVehicle.
        /// </summary>
        internal static string DrowningInVehicle {
            get {
                return ResourceManager.GetString("DrowningInVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectricFence.
        /// </summary>
        internal static string ElectricFence {
            get {
                return ResourceManager.GetString("ElectricFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhaustion.
        /// </summary>
        internal static string Exhaustion {
            get {
                return ResourceManager.GetString("Exhaustion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosion.
        /// </summary>
        internal static string Explosion {
            get {
                return ResourceManager.GetString("Explosion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall.
        /// </summary>
        internal static string Fall {
            get {
                return ResourceManager.GetString("Fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FireExtinguisher.
        /// </summary>
        internal static string FireExtinguisher {
            get {
                return ResourceManager.GetString("FireExtinguisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firework.
        /// </summary>
        internal static string Firework {
            get {
                return ResourceManager.GetString("Firework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flare.
        /// </summary>
        internal static string Flare {
            get {
                return ResourceManager.GetString("Flare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlareGun.
        /// </summary>
        internal static string FlareGun {
            get {
                return ResourceManager.GetString("FlareGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashlight.
        /// </summary>
        internal static string Flashlight {
            get {
                return ResourceManager.GetString("Flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GolfClub.
        /// </summary>
        internal static string GolfClub {
            get {
                return ResourceManager.GetString("GolfClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenade.
        /// </summary>
        internal static string Grenade {
            get {
                return ResourceManager.GetString("Grenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrenadeLauncher.
        /// </summary>
        internal static string GrenadeLauncher {
            get {
                return ResourceManager.GetString("GrenadeLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrenadeLauncherSmoke.
        /// </summary>
        internal static string GrenadeLauncherSmoke {
            get {
                return ResourceManager.GetString("GrenadeLauncherSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gusenberg.
        /// </summary>
        internal static string Gusenberg {
            get {
                return ResourceManager.GetString("Gusenberg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer.
        /// </summary>
        internal static string Hammer {
            get {
                return ResourceManager.GetString("Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatchet.
        /// </summary>
        internal static string Hatchet {
            get {
                return ResourceManager.GetString("Hatchet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeavyPistol.
        /// </summary>
        internal static string HeavyPistol {
            get {
                return ResourceManager.GetString("HeavyPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeavyShotgun.
        /// </summary>
        internal static string HeavyShotgun {
            get {
                return ResourceManager.GetString("HeavyShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeavySniper.
        /// </summary>
        internal static string HeavySniper {
            get {
                return ResourceManager.GetString("HeavySniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeliCrash.
        /// </summary>
        internal static string HeliCrash {
            get {
                return ResourceManager.GetString("HeliCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HitByWaterCannon.
        /// </summary>
        internal static string HitByWaterCannon {
            get {
                return ResourceManager.GetString("HitByWaterCannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomingLauncher.
        /// </summary>
        internal static string HomingLauncher {
            get {
                return ResourceManager.GetString("HomingLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knife.
        /// </summary>
        internal static string Knife {
            get {
                return ResourceManager.GetString("Knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnuckleDuster.
        /// </summary>
        internal static string KnuckleDuster {
            get {
                return ResourceManager.GetString("KnuckleDuster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machete.
        /// </summary>
        internal static string Machete {
            get {
                return ResourceManager.GetString("Machete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MachinePistol.
        /// </summary>
        internal static string MachinePistol {
            get {
                return ResourceManager.GetString("MachinePistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarksmanPistol.
        /// </summary>
        internal static string MarksmanPistol {
            get {
                return ResourceManager.GetString("MarksmanPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarksmanRifle.
        /// </summary>
        internal static string MarksmanRifle {
            get {
                return ResourceManager.GetString("MarksmanRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG.
        /// </summary>
        internal static string MG {
            get {
                return ResourceManager.GetString("MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicroSMG.
        /// </summary>
        internal static string MicroSMG {
            get {
                return ResourceManager.GetString("MicroSMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minigun.
        /// </summary>
        internal static string Minigun {
            get {
                return ResourceManager.GetString("Minigun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniSMG.
        /// </summary>
        internal static string MiniSMG {
            get {
                return ResourceManager.GetString("MiniSMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molotov.
        /// </summary>
        internal static string Molotov {
            get {
                return ResourceManager.GetString("Molotov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musket.
        /// </summary>
        internal static string Musket {
            get {
                return ResourceManager.GetString("Musket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightstick.
        /// </summary>
        internal static string Nightstick {
            get {
                return ResourceManager.GetString("Nightstick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NightVision.
        /// </summary>
        internal static string NightVision {
            get {
                return ResourceManager.GetString("NightVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parachute.
        /// </summary>
        internal static string Parachute {
            get {
                return ResourceManager.GetString("Parachute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PetrolCan.
        /// </summary>
        internal static string PetrolCan {
            get {
                return ResourceManager.GetString("PetrolCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PipeBomb.
        /// </summary>
        internal static string PipeBomb {
            get {
                return ResourceManager.GetString("PipeBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        internal static string Pistol {
            get {
                return ResourceManager.GetString("Pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol50.
        /// </summary>
        internal static string Pistol50 {
            get {
                return ResourceManager.GetString("Pistol50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoolCue.
        /// </summary>
        internal static string PoolCue {
            get {
                return ResourceManager.GetString("PoolCue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProximityMine.
        /// </summary>
        internal static string ProximityMine {
            get {
                return ResourceManager.GetString("ProximityMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PumpShotgun.
        /// </summary>
        internal static string PumpShotgun {
            get {
                return ResourceManager.GetString("PumpShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railgun.
        /// </summary>
        internal static string Railgun {
            get {
                return ResourceManager.GetString("Railgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Rammed.
        /// </summary>
        internal static string RammedByCar {
            get {
                return ResourceManager.GetString("RammedByCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolver.
        /// </summary>
        internal static string Revolver {
            get {
                return ResourceManager.GetString("Revolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPG.
        /// </summary>
        internal static string RPG {
            get {
                return ResourceManager.GetString("RPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Over.
        /// </summary>
        internal static string RunOverByCar {
            get {
                return ResourceManager.GetString("RunOverByCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SawnOffShotgun.
        /// </summary>
        internal static string SawnOffShotgun {
            get {
                return ResourceManager.GetString("SawnOffShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        internal static string SMG {
            get {
                return ResourceManager.GetString("SMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmokeGrenade.
        /// </summary>
        internal static string SmokeGrenade {
            get {
                return ResourceManager.GetString("SmokeGrenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SniperRifle.
        /// </summary>
        internal static string SniperRifle {
            get {
                return ResourceManager.GetString("SniperRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowball.
        /// </summary>
        internal static string Snowball {
            get {
                return ResourceManager.GetString("Snowball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNSPistol.
        /// </summary>
        internal static string SNSPistol {
            get {
                return ResourceManager.GetString("SNSPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialCarbine.
        /// </summary>
        internal static string SpecialCarbine {
            get {
                return ResourceManager.GetString("SpecialCarbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StickyBomb.
        /// </summary>
        internal static string StickyBomb {
            get {
                return ResourceManager.GetString("StickyBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StunGun.
        /// </summary>
        internal static string StunGun {
            get {
                return ResourceManager.GetString("StunGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SweeperShotgun.
        /// </summary>
        internal static string SweeperShotgun {
            get {
                return ResourceManager.GetString("SweeperShotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwitchBlade.
        /// </summary>
        internal static string SwitchBlade {
            get {
                return ResourceManager.GetString("SwitchBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unarmed.
        /// </summary>
        internal static string Unarmed {
            get {
                return ResourceManager.GetString("Unarmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleRocket.
        /// </summary>
        internal static string VehicleRocket {
            get {
                return ResourceManager.GetString("VehicleRocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VintagePistol.
        /// </summary>
        internal static string VintagePistol {
            get {
                return ResourceManager.GetString("VintagePistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrench.
        /// </summary>
        internal static string Wrench {
            get {
                return ResourceManager.GetString("Wrench", resourceCulture);
            }
        }
    }
}
