//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChatMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Localization.ChatMessages", typeof(ChatMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~o~Use /acmds to show commands.
        /// </summary>
        public static string AdminCmds {
            get {
                return ResourceManager.GetString("AdminCmds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left server.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kicked for.
        /// </summary>
        public static string Kicked {
            get {
                return ResourceManager.GetString("Kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~r~ERROR:~w~ ACL has been disabled on this server..
        /// </summary>
        public static string Login_ACLDisabled {
            get {
                return ResourceManager.GetString("Login_ACLDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~r~ERROR:~w~ You&apos;re already logged in!.
        /// </summary>
        public static string Login_AlreadyLogged {
            get {
                return ResourceManager.GetString("Login_AlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~r~ERROR:~w~ Wrong password!.
        /// </summary>
        public static string Login_BadPassword {
            get {
                return ResourceManager.GetString("Login_BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~b~ You&apos;re now logged out.
        /// </summary>
        public static string Login_Logout {
            get {
                return ResourceManager.GetString("Login_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~r~ERROR:~w~ No account found with your name..
        /// </summary>
        public static string Login_NoAccount {
            get {
                return ResourceManager.GetString("Login_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~g~Login successful!~w~ Logged in as .
        /// </summary>
        public static string Login_Success {
            get {
                return ResourceManager.GetString("Login_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~r~No resource found:.
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not running!.
        /// </summary>
        public static string ResourceNotRunning {
            get {
                return ResourceManager.GetString("ResourceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~g~Restarted resource .
        /// </summary>
        public static string ResourceRestarted {
            get {
                return ResourceManager.GetString("ResourceRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is already running!.
        /// </summary>
        public static string ResourceRunning {
            get {
                return ResourceManager.GetString("ResourceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~g~Stopped resource .
        /// </summary>
        public static string ResourceStopped {
            get {
                return ResourceManager.GetString("ResourceStopped", resourceCulture);
            }
        }
    }
}
